name: video_thumbnail

description: A flutter plugin for creating a thumbnail from a local video file or from a video URL.

version: 0.5.3

# author: John Zhong <john138@gmail.com>, Tairs Rzajevs <tairs.rzayevs@chi.lv>, Grigori <jlavyan@gmail.com>, Hafeez Ahmed <hahmed@fusionsd.com.au>, Leynier <leynier41@gmail.com>, Andreas Petrov, julek-kal, Nils Reichardt, Ajb Coder

homepage: https://github.com/justsoft

repository: https://github.com/justsoft/video_thumbnail

issue_tracker: https://github.com/justsoft/video_thumbnail/issues

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: xyz.justsoft.video_thumbnail
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin
